package com.odysee.app.core.designsystem.comments

data class EmoteDef(val name: String, val url: String, val unicode: String? = null)

private const val ODY_CDN = "https://static.odycdn.com/emoticons"
private fun ody(p: String) = "$ODY_CDN/$p"

val ODYSEE_EMOTES_48 = listOf(
    EmoteDef(":love_1:", ody("48%20px/Love%402x.png")),
    EmoteDef(":love_2:", ody("48%20px/Love%202%402x.png")),
    EmoteDef(":smile_1:", ody("48%20px/smile%402x.png")),
    EmoteDef(":smile_2:", ody("48%20px/smile%202%402x.png")),
    EmoteDef(":laughing_1:", ody("48%20px/Laughing%402x.png")),
    EmoteDef(":laughing_2:", ody("48%20px/Laughing 2%402x.png")),
    EmoteDef(":cry_2:", ody("48%20px/cry%202%402x.png")),
    EmoteDef(":cry_4:", ody("48%20px/cry%204%402x.png")),
    EmoteDef(":angry_1:", ody("48%20px/angry%402x.png")),
    EmoteDef(":angry_3:", ody("48%20px/angry%203%402x.png")),
    EmoteDef(":kiss_1:", ody("48%20px/kiss%402x.png")),
    EmoteDef(":surprised:", ody("48%20px/surprised%402x.png")),
    EmoteDef(":ouch:", ody("48%20px/ouch%402x.png")),
    EmoteDef(":confused_2:", ody("48%20px/confused%402x.png")),
    EmoteDef(":what:", ody("48%20px/what_%402x.png")),
    EmoteDef(":sad:", ody("48%20px/sad%402x.png")),
    EmoteDef(":angry_2:", ody("48%20px/angry%202%402x.png")),
    EmoteDef(":cry_1:", ody("48%20px/cry%402x.png")),
    EmoteDef(":cry_3:", ody("48%20px/cry%203%402x.png")),
    EmoteDef(":cry_5:", ody("48%20px/cry%205%402x.png")),
    EmoteDef(":sleep:", ody("48%20px/Sleep%402x.png")),
    EmoteDef(":thinking_2:", ody("48%20px/thinking%402x.png")),
    EmoteDef(":peace:", ody("48%20px/peace%402x.png")),
    EmoteDef(":no:", ody("48%20px/NO%402x.png")),
    EmoteDef(":block:", ody("48%20px/block%402x.png")),
    EmoteDef(":confirm:", ody("48%20px/CONFIRM%402x.png")),
    EmoteDef(":thumb_down:", ody("48%20px/thumb%20down%402x.png")),
    EmoteDef(":kiss_2:", ody("48%20px/kiss%202%402x.png")),
    EmoteDef(":angry_4:", ody("48%20px/angry%204%402x.png")),
    EmoteDef(":scary:", ody("48%20px/scary%402x.png")),
    EmoteDef(":alien:", ody("48%20px/Alien%402x.png")),
    EmoteDef(":blind:", ody("48%20px/blind%402x.png")),
    EmoteDef(":bomb:", ody("48%20px/bomb%402x.png")),
    EmoteDef(":brain_chip:", ody("48%20px/Brain%20chip%402x.png")),
    EmoteDef(":cooking_something_nice:", ody("48%20px/cooking%20something%20nice%402x.png")),
    EmoteDef(":donut:", ody("48%20px/donut%402x.png")),
    EmoteDef(":eggplant_with_condom:", ody("48%20px/eggplant%20with%20condom%402x.png")),
    EmoteDef(":eggplant:", ody("48%20px/eggplant%402x.png")),
    EmoteDef(":fire_up:", ody("48%20px/fire%20up%402x.png")),
    EmoteDef(":flat_earth:", ody("48%20px/Flat%20earth%402x.png")),
    EmoteDef(":flying_saucer:", ody("48%20px/Flying%20saucer%402x.png")),
    EmoteDef(":heart_chopper:", ody("48%20px/heart%20chopper%402x.png")),
    EmoteDef(":ice_cream:", ody("48%20px/ice%20cream%402x.png")),
    EmoteDef(":idk:", ody("48%20px/IDK%402x.png")),
    EmoteDef(":illuminati_2:", ody("48%20px/Illuminati%402x.png")),
    EmoteDef(":laser_gun:", ody("48%20px/laser%20gun%402x.png")),
    EmoteDef(":lollipop:", ody("48%20px/Lollipop%402x.png")),
    EmoteDef(":monster:", ody("48%20px/Monster%402x.png")),
    EmoteDef(":mushroom:", ody("48%20px/mushroom%402x.png")),
    EmoteDef(":nail_it:", ody("48%20px/Nail%20It%402x.png")),
    EmoteDef(":pizza:", ody("48%20px/pizza%402x.png")),
    EmoteDef(":rabbit_hole:", ody("48%20px/rabbit%20hole%402x.png")),
    EmoteDef(":rainbow_puke_2:", ody("48%20px/rainbow%20puke%402x.png")),
    EmoteDef(":rock:", ody("48%20px/ROCK%402x.png")),
    EmoteDef(":salty:", ody("48%20px/salty%402x.png")),
    EmoteDef(":slime_down:", ody("48%20px/slime%20down%402x.png")),
    EmoteDef(":smelly_socks:", ody("48%20px/smelly%20socks%402x.png")),
    EmoteDef(":spock:", ody("48%20px/SPOCK%402x.png")),
    EmoteDef(":star:", ody("48%20px/Star%402x.png")),
    EmoteDef(":sunny_day:", ody("48%20px/sunny%20day%402x.png")),
    EmoteDef(":sweet:", ody("48%20px/sweet%402x.png")),
    EmoteDef(":thumb_up_2:", ody("48%20px/thumb%20up%402x.png")),
    EmoteDef(":tinfoil_hat:", ody("48%20px/tin%20hat%402x.png")),
    EmoteDef(":troll_king:", ody("48%20px/Troll%20king%402x.png")),
    EmoteDef(":ufo:", ody("48%20px/ufo%402x.png")),
    EmoteDef(":woodoo_doll:", ody("48%20px/woodo%20doll%402x.png")),
    EmoteDef(":hyper_troll:", ody("48%20px/HyperTroll%402x.png")),
    EmoteDef(":space_chad:", ody("48%20px/space%20chad%402x.png")),
    EmoteDef(":space_doge:", ody("48%20px/doge%402x.png")),
    EmoteDef(":space_julian:", ody("48%20px/Space%20Julian%402x.png")),
    EmoteDef(":space_red_wojak:", ody("48%20px/space%20wojak%402x.png")),
    EmoteDef(":space_resitas:", ody("48%20px/resitas%402x.png")),
    EmoteDef(":space_tom:", ody("48%20px/space%20Tom%402x.png")),
    EmoteDef(":waiting:", ody("48%20px/waiting%402x.png")),
)

val TWEMOTES_SMILIES = listOf(
    EmoteDef(":grinning:", ody("twemoji/smilies/grinning.png"), "😀"),
    EmoteDef(":smiley:", ody("twemoji/smilies/smiley.png"), "😃"),
    EmoteDef(":smile:", ody("twemoji/smilies/smile.png"), "😄"),
    EmoteDef(":grin:", ody("twemoji/smilies/grin.png"), "😁"),
    EmoteDef(":laughing:", ody("twemoji/smilies/laughing.png"), "😆"),
    EmoteDef(":sweat_smile:", ody("twemoji/smilies/sweat_smile.png"), "😅"),
    EmoteDef(":joy:", ody("twemoji/smilies/joy.png"), "😂"),
    EmoteDef(":rofl:", ody("twemoji/smilies/rofl.png"), "🤣"),
    EmoteDef(":relaxed:", ody("twemoji/smilies/relaxed.png"), "☺"),
    EmoteDef(":blush:", ody("twemoji/smilies/blush.png"), "😊"),
    EmoteDef(":innocent:", ody("twemoji/smilies/innocent.png"), "😇"),
    EmoteDef(":slight_smile:", ody("twemoji/smilies/slight_smile.png"), "🙂"),
    EmoteDef(":upside_down_face:", ody("twemoji/smilies/upside_down_face.png"), "🙃"),
    EmoteDef(":wink:", ody("twemoji/smilies/wink.png"), "😉"),
    EmoteDef(":relieved:", ody("twemoji/smilies/relieved.png"), "😌"),
    EmoteDef(":smiling_face_with_tear:", ody("twemoji/smilies/smiling_face_with_tear.png"), "🥲"),
    EmoteDef(":heart_eyes:", ody("twemoji/smilies/heart_eyes.png"), "😍"),
    EmoteDef(":smiling_face_with_hearts:", ody("twemoji/smilies/smiling_face_with_hearts.png"), "🥰"),
    EmoteDef(":kissing_heart:", ody("twemoji/smilies/kissing_heart.png"), "😘"),
    EmoteDef(":kissing:", ody("twemoji/smilies/kissing.png"), "😗"),
    EmoteDef(":kissing_smiling_eyes:", ody("twemoji/smilies/kissing_smiling_eyes.png"), "😙"),
    EmoteDef(":kissing_closed_eyes:", ody("twemoji/smilies/kissing_closed_eyes.png"), "😚"),
    EmoteDef(":yum:", ody("twemoji/smilies/yum.png"), "😋"),
    EmoteDef(":stuck_out_tongue:", ody("twemoji/smilies/stuck_out_tongue.png"), "😛"),
    EmoteDef(":stuck_out_tongue_closed_eyes:", ody("twemoji/smilies/stuck_out_tongue_closed_eyes.png"), "😝"),
    EmoteDef(":stuck_out_tongue_winking_eye:", ody("twemoji/smilies/stuck_out_tongue_winking_eye.png"), "😜"),
    EmoteDef(":zany:", ody("twemoji/smilies/zany.png"), "🤪"),
    EmoteDef(":raised_eyebrow:", ody("twemoji/smilies/raised_eyebrow.png"), "🤨"),
    EmoteDef(":monocle:", ody("twemoji/smilies/monocle.png"), "🧐"),
    EmoteDef(":nerd_face:", ody("twemoji/smilies/nerd_face.png"), "🤓"),
    EmoteDef(":sunglasses:", ody("twemoji/smilies/sunglasses.png"), "😎"),
    EmoteDef(":star_struck:", ody("twemoji/smilies/star_struck.png"), "🤩"),
    EmoteDef(":partying:", ody("twemoji/smilies/partying.png"), "🥳"),
    EmoteDef(":smirk:", ody("twemoji/smilies/smirk.png"), "😏"),
    EmoteDef(":unamused:", ody("twemoji/smilies/unamused.png"), "😒"),
    EmoteDef(":disappointed:", ody("twemoji/smilies/disappointed.png"), "😞"),
    EmoteDef(":pensive:", ody("twemoji/smilies/pensive.png"), "😔"),
    EmoteDef(":worried:", ody("twemoji/smilies/worried.png"), "😟"),
    EmoteDef(":confused:", ody("twemoji/smilies/confused.png"), "😕"),
    EmoteDef(":slightly_frowning_face:", ody("twemoji/smilies/slightly_frowning_face.png"), "🙁"),
    EmoteDef(":frowning_face:", ody("twemoji/smilies/frowning_face.png"), "☹"),
    EmoteDef(":persevere:", ody("twemoji/smilies/persevere.png"), "😣"),
    EmoteDef(":confounded:", ody("twemoji/smilies/confounded.png"), "😖"),
    EmoteDef(":tired_face:", ody("twemoji/smilies/tired_face.png"), "😫"),
    EmoteDef(":weary:", ody("twemoji/smilies/weary.png"), "😩"),
    EmoteDef(":pleading:", ody("twemoji/smilies/pleading.png"), "🥺"),
    EmoteDef(":cry:", ody("twemoji/smilies/cry.png"), "😢"),
    EmoteDef(":sob:", ody("twemoji/smilies/sob.png"), "😭"),
    EmoteDef(":triump:", ody("twemoji/smilies/triumph.png"), "😤"),
    EmoteDef(":exhaling:", ody("twemoji/smilies/exhaling.png"), "😮‍💨"),
    EmoteDef(":angry:", ody("twemoji/smilies/angry.png"), "😠"),
    EmoteDef(":rage:", ody("twemoji/smilies/rage.png"), "😡"),
    EmoteDef(":symbols_over_mouth:", ody("twemoji/smilies/symbols_over_mouth.png"), "🤬"),
    EmoteDef(":exploding_head:", ody("twemoji/smilies/exploding_head.png"), "🤯"),
    EmoteDef(":flushed:", ody("twemoji/smilies/flushed.png"), "😳"),
    EmoteDef(":face_in_clouds:", ody("twemoji/smilies/face_in_clouds.png"), "😶‍🌫️"),
    EmoteDef(":hot:", ody("twemoji/smilies/hot.png"), "🥵"),
    EmoteDef(":cold:", ody("twemoji/smilies/cold.png"), "🥶"),
    EmoteDef(":scream:", ody("twemoji/smilies/scream.png"), "😱"),
    EmoteDef(":fearful:", ody("twemoji/smilies/fearful.png"), "😨"),
    EmoteDef(":cold_sweat:", ody("twemoji/smilies/cold_sweat.png"), "😰"),
    EmoteDef(":disappointed_relieved:", ody("twemoji/smilies/disappointed_relieved.png"), "😥"),
    EmoteDef(":sweat:", ody("twemoji/smilies/sweat.png"), "😅"),
    EmoteDef(":hugging:", ody("twemoji/smilies/hugging.png"), "🤗"),
    EmoteDef(":thinking:", ody("twemoji/smilies/thinking.png"), "🤔"),
    EmoteDef(":hand_over_mouth:", ody("twemoji/smilies/hand_over_mouth.png"), "🤭"),
    EmoteDef(":yawning:", ody("twemoji/smilies/yawning.png"), "🥱"),
    EmoteDef(":shushing:", ody("twemoji/smilies/shushing.png"), "🤫"),
    EmoteDef(":lying_face:", ody("twemoji/smilies/lying_face.png"), "🤥"),
    EmoteDef(":no_mouth:", ody("twemoji/smilies/no_mouth.png"), "😶"),
    EmoteDef(":neutral_face:", ody("twemoji/smilies/neutral_face.png"), "😐"),
    EmoteDef(":expressionless:", ody("twemoji/smilies/expressionless.png"), "😑"),
    EmoteDef(":grimacing:", ody("twemoji/smilies/grimacing.png"), "😬"),
    EmoteDef(":roll_eyes:", ody("twemoji/smilies/roll_eyes.png"), "🙄"),
    EmoteDef(":hushed:", ody("twemoji/smilies/hushed.png"), "😯"),
    EmoteDef(":frowning:", ody("twemoji/smilies/frowning.png"), "☹"),
    EmoteDef(":anguished:", ody("twemoji/smilies/anguished.png"), "😧"),
    EmoteDef(":open_mouth:", ody("twemoji/smilies/open_mouth.png"), "😮"),
    EmoteDef(":astonished:", ody("twemoji/smilies/astonished.png"), "😲"),
    EmoteDef(":sleeping:", ody("twemoji/smilies/sleeping.png"), "😴"),
    EmoteDef(":drooling_face:", ody("twemoji/smilies/drooling_face.png"), "🤤"),
    EmoteDef(":sleepy:", ody("twemoji/smilies/sleepy.png"), "😪"),
    EmoteDef(":dizzy_face:", ody("twemoji/smilies/dizzy_face.png"), "😵"),
    EmoteDef(":spiral_eyes:", ody("twemoji/smilies/spiral_eyes.png"), "😵‍💫"),
    EmoteDef(":zipper_mouth_face:", ody("twemoji/smilies/zipper_mouth_face.png"), "🤐"),
    EmoteDef(":woozy:", ody("twemoji/smilies/woozy.png"), "🥴"),
    EmoteDef(":nauseated_face:", ody("twemoji/smilies/nauseated_face.png"), "🤢"),
    EmoteDef(":vomiting:", ody("twemoji/smilies/vomiting.png"), "🤮"),
    EmoteDef(":sneezing_face:", ody("twemoji/smilies/sneezing_face.png"), "🤧"),
    EmoteDef(":mask:", ody("twemoji/smilies/mask.png"), "😷"),
    EmoteDef(":face_with_thermometer:", ody("twemoji/smilies/face_with_thermometer.png"), "🤒"),
    EmoteDef(":face_with_head_bandage:", ody("twemoji/smilies/face_with_head_bandage.png"), "🤕"),
    EmoteDef(":money_mouth_face:", ody("twemoji/smilies/money_mouth_face.png"), "🤑"),
    EmoteDef(":cowboy_hat_face:", ody("twemoji/smilies/cowboy_hat_face.png"), "🤠"),
    EmoteDef(":disguised_face:", ody("twemoji/smilies/disguised_face.png"), "🥸"),
    EmoteDef(":smiling_imp:", ody("twemoji/smilies/smiling_imp.png"), "😈"),
    EmoteDef(":imp:", ody("twemoji/smilies/imp.png"), "👿"),
    EmoteDef(":japanese_ogre:", ody("twemoji/smilies/japanese_ogre.png"), "👹"),
    EmoteDef(":japanese_goblin:", ody("twemoji/smilies/japanese_goblin.png"), "👺"),
    EmoteDef(":clown_face:", ody("twemoji/smilies/clown_face.png"), "🤡"),
    EmoteDef(":skull:", ody("twemoji/smilies/skull.png"), "💀"),
    EmoteDef(":alien_1:", ody("twemoji/smilies/alien_1.png"), "👽"),
    EmoteDef(":robot:", ody("twemoji/smilies/robot.png"), "🤖"),
    EmoteDef(":space_invader:", ody("twemoji/smilies/space_invader.png"), "👾"),
    EmoteDef(":santa_claus:", ody("twemoji/smilies/santa_claus.png"), "🎅"),
    EmoteDef(":full_moon_face:", ody("twemoji/smilies/full_moon_face.png"), "🌝"),
    EmoteDef(":new_moon_face:", ody("twemoji/smilies/new_moon_face.png"), "🌚"),
    EmoteDef(":jack_o_lantern:", ody("twemoji/smilies/jack_o_lantern.png"), "🎃"),
    EmoteDef(":moai:", ody("twemoji/smilies/moai.png"), "🗿"),
    EmoteDef(":melting_face:", ody("twemoji/smilies/melting_face.png"), "🫠"),
)

val TWEMOTES_HANDSIGNALS = listOf(
    EmoteDef(":thumbs_up:", ody("twemoji/handsignals/thumbs_up.png"), "👍"),
    EmoteDef(":thumbs_down:", ody("twemoji/handsignals/thumbs_down.png"), "👎"),
    EmoteDef(":raised_hand:", ody("twemoji/handsignals/raised_hand.png"), "✋"),
    EmoteDef(":raised_back_of_hand:", ody("twemoji/handsignals/raised_back_of_hand.png"), "🤚"),
    EmoteDef(":raised_hand_with_fingers_splayed:", ody("twemoji/handsignals/raised_hand_with_fingers_splayed.png"), "🖐"),
    EmoteDef(":waving_hand:", ody("twemoji/handsignals/waving_hand.png"), "👋"),
    EmoteDef(":vulcan_salute:", ody("twemoji/handsignals/vulcan_salute.png"), "🖖"),
    EmoteDef(":rightwards_hand:", ody("twemoji/handsignals/rightwards_hand.png"), "🫱"),
    EmoteDef(":leftwards_hand:", ody("twemoji/handsignals/leftwards_hand.png"), "🫲"),
    EmoteDef(":palm_down_hand:", ody("twemoji/handsignals/palm_down_hand.png"), "🫳"),
    EmoteDef(":palm_up_hand:", ody("twemoji/handsignals/palm_up_hand.png"), "🫴"),
    EmoteDef(":ok_hand:", ody("twemoji/handsignals/ok_hand.png"), "👌"),
    EmoteDef(":pinched_fingers:", ody("twemoji/handsignals/pinched_fingers.png"), "🤌"),
    EmoteDef(":pinching_hand:", ody("twemoji/handsignals/pinching_hand.png"), "🤏"),
    EmoteDef(":victory_hand:", ody("twemoji/handsignals/victory_hand.png"), "✌"),
    EmoteDef(":crossed_fingers:", ody("twemoji/handsignals/crossed_fingers.png"), "🤞"),
    EmoteDef(":love_you_gesture:", ody("twemoji/handsignals/love_you_gesture.png"), "🤟"),
    EmoteDef(":sign_of_the_horns:", ody("twemoji/handsignals/sign_of_the_horns.png"), "🤘"),
    EmoteDef(":call_me_hand:", ody("twemoji/handsignals/call_me_hand.png"), "🤙"),
    EmoteDef(":backhand_index_pointing_left:", ody("twemoji/handsignals/backhand_index_pointing_left.png"), "👈"),
    EmoteDef(":backhand_index_pointing_right:", ody("twemoji/handsignals/backhand_index_pointing_right.png"), "👉"),
    EmoteDef(":backhand_index_pointing_up:", ody("twemoji/handsignals/backhand_index_pointing_up.png"), "👆"),
    EmoteDef(":backhand_index_pointing_down:", ody("twemoji/handsignals/backhand_index_pointing_down.png"), "👇"),
    EmoteDef(":middle_finger:", ody("twemoji/handsignals/middle_finger.png"), "🖕"),
    EmoteDef(":index_pointing_up:", ody("twemoji/handsignals/index_pointing_up.png"), "☝"),
    EmoteDef(":index_pointing_at_the_viewer:", ody("twemoji/handsignals/index_pointing_at_the_viewer.png"), "🫵"),
    EmoteDef(":raised_fist:", ody("twemoji/handsignals/raised_fist.png"), "✊"),
    EmoteDef(":oncoming_fist:", ody("twemoji/handsignals/oncoming_fist.png"), "👊"),
    EmoteDef(":left_facing_fist:", ody("twemoji/handsignals/left_facing_fist.png"), "🤛"),
    EmoteDef(":right_facing_fist:", ody("twemoji/handsignals/right_facing_fist.png"), "🤜"),
    EmoteDef(":clapping_hands:", ody("twemoji/handsignals/clapping_hands.png"), "👏"),
    EmoteDef(":raising_hands:", ody("twemoji/handsignals/raising_hands.png"), "🙌"),
    EmoteDef(":heart_hands:", ody("twemoji/handsignals/heart_hands.png"), "🫶"),
    EmoteDef(":open_hands:", ody("twemoji/handsignals/open_hands.png"), "👐"),
    EmoteDef(":palms_up_together:", ody("twemoji/handsignals/palms_up_together.png"), "🤲"),
    EmoteDef(":handshake:", ody("twemoji/handsignals/handshake.png"), "🤝"),
    EmoteDef(":folded_hands:", ody("twemoji/handsignals/folded_hands.png"), "🙏"),
)

val TWEMOTES_NATURE = listOf(
    EmoteDef(":dog:", ody("twemoji/nature/dog.png"), "🐶"),
    EmoteDef(":cat:", ody("twemoji/nature/cat.png"), "🐱"),
    EmoteDef(":mouse:", ody("twemoji/nature/mouse.png"), "🐭"),
    EmoteDef(":hamster:", ody("twemoji/nature/hamster.png"), "🐹"),
    EmoteDef(":rabbit:", ody("twemoji/nature/rabbit.png"), "🐰"),
    EmoteDef(":fox:", ody("twemoji/nature/fox.png"), "🦊"),
    EmoteDef(":wolf:", ody("twemoji/nature/wolf.png"), "🐺"),
    EmoteDef(":bear:", ody("twemoji/nature/bear.png"), "🐻"),
    EmoteDef(":panda:", ody("twemoji/nature/panda.png"), "🐼"),
    EmoteDef(":polar_bear:", ody("twemoji/nature/polar_bear.png"), "🐻‍❄️"),
    EmoteDef(":koala:", ody("twemoji/nature/koala.png"), "🐨"),
    EmoteDef(":tiger:", ody("twemoji/nature/tiger.png"), "🐯"),
    EmoteDef(":lion:", ody("twemoji/nature/lion.png"), "🦁"),
    EmoteDef(":cow:", ody("twemoji/nature/cow.png"), "🐮"),
    EmoteDef(":pig:", ody("twemoji/nature/pig.png"), "🐷"),
    EmoteDef(":boar:", ody("twemoji/nature/boar.png"), "🐗"),
    EmoteDef(":frog:", ody("twemoji/nature/frog.png"), "🐸"),
    EmoteDef(":gorilla:", ody("twemoji/nature/gorilla.png"), "🦍"),
    EmoteDef(":monkey:", ody("twemoji/nature/monkey.png"), "🐵"),
    EmoteDef(":see_no_evil:", ody("twemoji/nature/see_no_evil.png"), "🙈"),
    EmoteDef(":hear_no_evil:", ody("twemoji/nature/hear_no_evil.png"), "🙉"),
    EmoteDef(":speak_no_evil:", ody("twemoji/nature/speak_no_evil.png"), "🙊"),
    EmoteDef(":chicken:", ody("twemoji/nature/chicken.png"), "🐔"),
    EmoteDef(":eagle:", ody("twemoji/nature/eagle.png"), "🦅"),
    EmoteDef(":flamingo:", ody("twemoji/nature/flamingo.png"), "🦩"),
    EmoteDef(":penguin:", ody("twemoji/nature/penguin.png"), "🐧"),
    EmoteDef(":owl:", ody("twemoji/nature/owl.png"), "🦉"),
    EmoteDef(":parrot:", ody("twemoji/nature/parrot.png"), "🦜"),
    EmoteDef(":duck:", ody("twemoji/nature/duck.png"), "🦆"),
    EmoteDef(":swan:", ody("twemoji/nature/swan.png"), "🦢"),
    EmoteDef(":dove:", ody("twemoji/nature/dove.png"), "🕊"),
    EmoteDef(":peacock:", ody("twemoji/nature/peacock.png"), "🦚"),
    EmoteDef(":dodo:", ody("twemoji/nature/dodo.png"), "🦤"),
    EmoteDef(":bird:", ody("twemoji/nature/bird.png"), "🐦"),
    EmoteDef(":raccoon:", ody("twemoji/nature/raccoon.png"), "🦝"),
    EmoteDef(":hedgehog:", ody("twemoji/nature/hedgehog.png"), "🦔"),
    EmoteDef(":sloth:", ody("twemoji/nature/sloth.png"), "🦥"),
    EmoteDef(":bat:", ody("twemoji/nature/bat.png"), "🦇"),
    EmoteDef(":otter:", ody("twemoji/nature/otter.png"), "🦦"),
    EmoteDef(":skunk:", ody("twemoji/nature/skunk.png"), "🦨"),
    EmoteDef(":deer:", ody("twemoji/nature/deer.png"), "🦌"),
    EmoteDef(":camel:", ody("twemoji/nature/camel.png"), "🐫"),
    EmoteDef(":llama:", ody("twemoji/nature/llama.png"), "🦙"),
    EmoteDef(":goat:", ody("twemoji/nature/goat.png"), "🐐"),
    EmoteDef(":giraffe:", ody("twemoji/nature/giraffe.png"), "🦒"),
    EmoteDef(":elephant:", ody("twemoji/nature/elephant.png"), "🐘"),
    EmoteDef(":mammoth:", ody("twemoji/nature/mammoth.png"), "🦣"),
    EmoteDef(":leopard:", ody("twemoji/nature/leopard.png"), "🐆"),
    EmoteDef(":rhinoceros:", ody("twemoji/nature/rhinoceros.png"), "🦏"),
    EmoteDef(":hippopotamus:", ody("twemoji/nature/hippopotamus.png"), "🦛"),
    EmoteDef(":bison:", ody("twemoji/nature/bison.png"), "🦬"),
    EmoteDef(":kangaroo:", ody("twemoji/nature/kangaroo.png"), "🦘"),
    EmoteDef(":horse_face:", ody("twemoji/nature/horse_face.png"), "🐴"),
    EmoteDef(":zebra:", ody("twemoji/nature/zebra.png"), "🦓"),
    EmoteDef(":unicorn:", ody("twemoji/nature/unicorn.png"), "🦄"),
    EmoteDef(":dragon_face:", ody("twemoji/nature/dragon_face.png"), "🐲"),
    EmoteDef(":t-rex:", ody("twemoji/nature/t-rex.png"), "🦖"),
    EmoteDef(":sauropod:", ody("twemoji/nature/sauropod.png"), "🦕"),
    EmoteDef(":snake:", ody("twemoji/nature/snake.png"), "🐍"),
    EmoteDef(":lizard:", ody("twemoji/nature/lizard.png"), "🦎"),
    EmoteDef(":crocodile:", ody("twemoji/nature/crocodile.png"), "🐊"),
    EmoteDef(":turtle:", ody("twemoji/nature/turtle.png"), "🐢"),
    EmoteDef(":whale:", ody("twemoji/nature/whale.png"), "🐋"),
    EmoteDef(":dolphin:", ody("twemoji/nature/dolphin.png"), "🐬"),
    EmoteDef(":seal:", ody("twemoji/nature/seal.png"), "🦭"),
    EmoteDef(":fish:", ody("twemoji/nature/fish.png"), "🐟"),
    EmoteDef(":tropical_fish:", ody("twemoji/nature/tropical_fish.png"), "🐠"),
    EmoteDef(":blowfish:", ody("twemoji/nature/blowfish.png"), "🐡"),
    EmoteDef(":shark:", ody("twemoji/nature/shark.png"), "🦈"),
    EmoteDef(":spiral_shell:", ody("twemoji/nature/spiral_shell.png"), "🐚"),
    EmoteDef(":crab:", ody("twemoji/nature/crab.png"), "🦀"),
    EmoteDef(":lobster:", ody("twemoji/nature/lobster.png"), "🦞"),
    EmoteDef(":shrimp:", ody("twemoji/nature/shrimp.png"), "🦐"),
    EmoteDef(":octopus:", ody("twemoji/nature/octopus.png"), "🐙"),
    EmoteDef(":squid:", ody("twemoji/nature/squid.png"), "🦑"),
    EmoteDef(":snail:", ody("twemoji/nature/snail.png"), "🐌"),
    EmoteDef(":butterfly:", ody("twemoji/nature/butterfly.png"), "🦋"),
    EmoteDef(":bug:", ody("twemoji/nature/bug.png"), "🐛"),
    EmoteDef(":ant:", ody("twemoji/nature/ant.png"), "🐜"),
    EmoteDef(":honeybee:", ody("twemoji/nature/honeybee.png"), "🐝"),
    EmoteDef(":beetle:", ody("twemoji/nature/beetle.png"), "🪲"),
    EmoteDef(":lady_beetle:", ody("twemoji/nature/lady_beetle.png"), "🐞"),
    EmoteDef(":cricket:", ody("twemoji/nature/cricket.png"), "🦗"),
    EmoteDef(":cockroach:", ody("twemoji/nature/cockroach.png"), "🪳"),
    EmoteDef(":spider:", ody("twemoji/nature/spider.png"), "🕷"),
    EmoteDef(":scorpion:", ody("twemoji/nature/scorpion.png"), "🦂"),
    EmoteDef(":mosquito:", ody("twemoji/nature/mosquito.png"), "🦟"),
    EmoteDef(":fly:", ody("twemoji/nature/fly.png"), "🪰"),
    EmoteDef(":worm:", ody("twemoji/nature/worm.png"), "🪱"),
    EmoteDef(":deciduous_tree:", ody("twemoji/nature/deciduous_tree.png"), "🌳"),
    EmoteDef(":evergreen_tree:", ody("twemoji/nature/evergreen_tree.png"), "🌲"),
    EmoteDef(":palm_tree:", ody("twemoji/nature/palm_tree.png"), "🌴"),
    EmoteDef(":cactus:", ody("twemoji/nature/cactus.png"), "🌵"),
    EmoteDef(":herb:", ody("twemoji/nature/herb.png"), "🌿"),
    EmoteDef(":lotus:", ody("twemoji/nature/lotus.png"), "🪷"),
    EmoteDef(":cherry_blossom:", ody("twemoji/nature/cherry_blossom.png"), "🌸"),
    EmoteDef(":tulip:", ody("twemoji/nature/tulip.png"), "🌷"),
    EmoteDef(":rose:", ody("twemoji/nature/rose.png"), "🌹"),
)

val TWEMOTES_ACTIVITIES = listOf(
    EmoteDef(":soccer:", ody("twemoji/activities/soccer.png"), "⚽"),
    EmoteDef(":american_football:", ody("twemoji/activities/american_football.png"), "🏈"),
    EmoteDef(":basketball:", ody("twemoji/activities/basketball.png"), "🏀"),
    EmoteDef(":baseball:", ody("twemoji/activities/baseball.png"), "⚾"),
    EmoteDef(":tennis:", ody("twemoji/activities/tennis.png"), "🎾"),
    EmoteDef(":volleyball:", ody("twemoji/activities/volleyball.png"), "🏐"),
    EmoteDef(":softball:", ody("twemoji/activities/softball.png"), "🥎"),
    EmoteDef(":rugby_football:", ody("twemoji/activities/rugby_football.png"), "🏉"),
    EmoteDef(":ping_pong:", ody("twemoji/activities/ping_pong.png"), "🏓"),
    EmoteDef(":ice_hockey:", ody("twemoji/activities/ice_hockey.png"), "🏒"),
    EmoteDef(":field_hockey:", ody("twemoji/activities/field_hockey.png"), "🏑"),
    EmoteDef(":bowling:", ody("twemoji/activities/bowling.png"), "🎳"),
    EmoteDef(":cricket_game:", ody("twemoji/activities/cricket_game.png"), "🏏"),
    EmoteDef(":lacrosse:", ody("twemoji/activities/lacrosse.png"), "🥍"),
    EmoteDef(":dart:", ody("twemoji/activities/dart.png"), "🎯"),
    EmoteDef(":badminton:", ody("twemoji/activities/badminton.png"), "🏸"),
    EmoteDef(":curling_stone:", ody("twemoji/activities/curling_stone.png"), "🥌"),
    EmoteDef(":boxing_glove:", ody("twemoji/activities/boxing_glove.png"), "🥊"),
    EmoteDef(":martial_arts_uniform:", ody("twemoji/activities/martial_arts_uniform.png"), "🥋"),
    EmoteDef(":golf:", ody("twemoji/activities/golf.png"), "⛳"),
    EmoteDef(":flying_disc:", ody("twemoji/activities/flying_disc.png"), "🥏"),
    EmoteDef(":diving_mask:", ody("twemoji/activities/diving_mask.png"), "🤿"),
    EmoteDef(":pc:", ody("twemoji/activities/pc.png"), ":pc:"),
    EmoteDef(":switch:", ody("twemoji/activities/switch.png"), ":switch:"),
    EmoteDef(":ps5:", ody("twemoji/activities/ps5.png"), ":ps5:"),
    EmoteDef(":xbox:", ody("twemoji/activities/xbox.png"), ":xbox:"),
    EmoteDef(":vr:", ody("twemoji/activities/vr.png"), ":vr:"),
    EmoteDef(":video_game:", ody("twemoji/activities/video_game.png"), "🎮"),
    EmoteDef(":joystick:", ody("twemoji/activities/joystick.png"), "🕹"),
    EmoteDef(":smartphone:", ody("twemoji/activities/smartphone.png"), "📱"),
    EmoteDef(":gameboy:", ody("twemoji/activities/gameboy.png"), ":gameboy:"),
    EmoteDef(":arcade:", ody("twemoji/activities/arcade.png"), ":arcade:"),
    EmoteDef(":slot_machine:", ody("twemoji/activities/slot_machine.png"), "🎰"),
    EmoteDef(":carousel_horse:", ody("twemoji/activities/carousel_horse.png"), "🎠"),
    EmoteDef(":playground_slide:", ody("twemoji/activities/playground_slide.png"), "🛝"),
    EmoteDef(":skateboard:", ody("twemoji/activities/skateboard.png"), "🛹"),
    EmoteDef(":canoe:", ody("twemoji/activities/canoe.png"), "🛶"),
    EmoteDef(":sailboat:", ody("twemoji/activities/sailboat.png"), "⛵"),
    EmoteDef(":roller_skate:", ody("twemoji/activities/roller_skate.png"), "🛼"),
    EmoteDef(":kick_scooter:", ody("twemoji/activities/kick_scooter.png"), "🛴"),
    EmoteDef(":bicycle:", ody("twemoji/activities/bicycle.png"), "🚲"),
    EmoteDef(":motor_scooter:", ody("twemoji/activities/motor_scooter.png"), "🛵"),
    EmoteDef(":motorcycle:", ody("twemoji/activities/motorcycle.png"), "🏍"),
    EmoteDef(":tractor:", ody("twemoji/activities/tractor.png"), "🚜"),
    EmoteDef(":automobile:", ody("twemoji/activities/automobile.png"), "🚗"),
    EmoteDef(":minibus:", ody("twemoji/activities/minibus.png"), "🚐"),
    EmoteDef(":bus:", ody("twemoji/activities/bus.png"), "🚌"),
    EmoteDef(":trolleybus:", ody("twemoji/activities/trolleybus.png"), "🚎"),
    EmoteDef(":train:", ody("twemoji/activities/train.png"), "🚆"),
    EmoteDef(":racing_car:", ody("twemoji/activities/racing_car.png"), "🏎"),
    EmoteDef(":helicopter:", ody("twemoji/activities/helicopter.png"), "🚁"),
    EmoteDef(":airplane:", ody("twemoji/activities/airplane.png"), "✈"),
    EmoteDef(":parachute:", ody("twemoji/activities/parachute.png"), "🪂"),
    EmoteDef(":rocket:", ody("twemoji/activities/rocket.png"), "🚀"),
    EmoteDef(":flying_saucer:", ody("twemoji/activities/flying_saucer.png"), "🛸"),
    EmoteDef(":game_die:", ody("twemoji/activities/game_die.png"), "🎲"),
    EmoteDef(":artist_palette:", ody("twemoji/activities/artist_palette.png"), "🎨"),
    EmoteDef(":fishing_pole:", ody("twemoji/activities/fishing_pole.png"), "🎣"),
    EmoteDef(":magic_wand:", ody("twemoji/activities/magic_wand.png"), "🪄"),
    EmoteDef(":crystal_ball:", ody("twemoji/activities/crystal_ball.png"), "🔮"),
    EmoteDef(":backpack:", ody("twemoji/activities/backpack.png"), "🎒"),
    EmoteDef(":sewing_needle:", ody("twemoji/activities/sewing_needle.png"), "🪡"),
    EmoteDef(":headphone:", ody("twemoji/activities/headphone.png"), "🎧"),
    EmoteDef(":microphone:", ody("twemoji/activities/microphone.png"), "🎤"),
    EmoteDef(":boomerang:", ody("twemoji/activities/boomerang.png"), "🪃"),
    EmoteDef(":bow_and_arrow:", ody("twemoji/activities/bow_and_arrow.png"), "🏹"),
    EmoteDef(":guitar:", ody("twemoji/activities/guitar.png"), "🎸"),
    EmoteDef(":drum:", ody("twemoji/activities/drum.png"), "🥁"),
    EmoteDef(":violin:", ody("twemoji/activities/violin.png"), "🎻"),
    EmoteDef(":trumpet:", ody("twemoji/activities/trumpet.png"), "🎺"),
    EmoteDef(":saxophone:", ody("twemoji/activities/saxophone.png"), "🎷"),
    EmoteDef(":accordion:", ody("twemoji/activities/accordion.png"), "🪗"),
    EmoteDef(":banjo:", ody("twemoji/activities/banjo.png"), "🪕"),
    EmoteDef(":long_drum:", ody("twemoji/activities/long_drum.png"), "🪘"),
    EmoteDef(":postal_horn:", ody("twemoji/activities/postal_horn.png"), "📯"),
    EmoteDef(":musical_keyboard:", ody("twemoji/activities/musical_keyboard.png"), "🎹"),
    EmoteDef(":musical_score:", ody("twemoji/activities/musical_score.png"), "🎼"),
    EmoteDef(":scissors:", ody("twemoji/activities/scissors.png"), "✂"),
    EmoteDef(":straight_ruler:", ody("twemoji/activities/straight_ruler.png"), "📏"),
    EmoteDef(":microscope:", ody("twemoji/activities/microscope.png"), "🔬"),
    EmoteDef(":hammer_and_pick:", ody("twemoji/activities/hammer_and_pick.png"), "⚒"),
    EmoteDef(":hammer_and_wrench:", ody("twemoji/activities/hammer_and_wrench.png"), "🛠"),
    EmoteDef(":hammer:", ody("twemoji/activities/hammer.png"), "🔨"),
    EmoteDef(":axe:", ody("twemoji/activities/axe.png"), "🪓"),
    EmoteDef(":pick:", ody("twemoji/activities/pick.png"), "⛏"),
    EmoteDef(":carpentry_saw:", ody("twemoji/activities/carpentry_saw.png"), "🪚"),
    EmoteDef(":wrench:", ody("twemoji/activities/wrench.png"), "🔧"),
    EmoteDef(":screwdriver:", ody("twemoji/activities/screwdriver.png"), "🪛"),
    EmoteDef(":toilet:", ody("twemoji/activities/toilet.png"), "🚽"),
    EmoteDef(":shower:", ody("twemoji/activities/shower.png"), "🚿"),
    EmoteDef(":bathtub:", ody("twemoji/activities/bathtub.png"), "🛁"),
    EmoteDef(":razor:", ody("twemoji/activities/razor.png"), "🪒"),
    EmoteDef(":toothbrush:", ody("twemoji/activities/toothbrush.png"), "🪥"),
    EmoteDef(":cigarette:", ody("twemoji/activities/cigarette.png"), "🚬"),
    EmoteDef(":broom:", ody("twemoji/activities/broom.png"), "🧹"),
    EmoteDef(":bucket:", ody("twemoji/activities/bucket.png"), "🪣"),
    EmoteDef(":plunger:", ody("twemoji/activities/plunger.png"), "🪠"),
    EmoteDef(":pill:", ody("twemoji/activities/pill.png"), "💊"),
    EmoteDef(":adhesive_bandage:", ody("twemoji/activities/adhesive_bandage.png"), "🩹"),
)

val TWEMOTES_SYMBOLS = listOf(
    EmoteDef(":heart:", ody("twemoji/symbols/heart.png"), "❤"),
    EmoteDef(":orange_hear:", ody("twemoji/symbols/orange_hear.png"), "🧡"),
    EmoteDef(":yellow_heart:", ody("twemoji/symbols/yellow_heart.png"), "💛"),
    EmoteDef(":green_heart:", ody("twemoji/symbols/green_heart.png"), "💚"),
    EmoteDef(":blue_heart:", ody("twemoji/symbols/blue_heart.png"), "💙"),
    EmoteDef(":purple_heart:", ody("twemoji/symbols/purple_heart.png"), "💜"),
    EmoteDef(":brown_heart:", ody("twemoji/symbols/brown_heart.png"), "🤎"),
    EmoteDef(":black_heart:", ody("twemoji/symbols/black_heart.png"), "🖤"),
    EmoteDef(":white_heart:", ody("twemoji/symbols/white_heart.png"), "🤍"),
    EmoteDef(":growing_heart:", ody("twemoji/symbols/growing_heart.png"), "💗"),
    EmoteDef(":sparkling_heart:", ody("twemoji/symbols/sparkling_heart.png"), "💖"),
    EmoteDef(":heart_with_ribbon:", ody("twemoji/symbols/heart_with_ribbon.png"), "💝"),
    EmoteDef(":mending_heart:", ody("twemoji/symbols/mending_heart.png"), "❤️‍🩹"),
    EmoteDef(":broken_heart:", ody("twemoji/symbols/broken_heart.png"), "💔"),
    EmoteDef(":beating_heart:", ody("twemoji/symbols/beating_heart.png"), "💓"),
    EmoteDef(":heart_with_arrow:", ody("twemoji/symbols/heart_with_arrow.png"), "💘"),
    EmoteDef(":revolving_hearts:", ody("twemoji/symbols/revolving_hearts.png"), "💞"),
    EmoteDef(":two_hearts:", ody("twemoji/symbols/two_hearts.png"), "💕"),
    EmoteDef(":heart_exclamation:", ody("twemoji/symbols/heart_exclamation.png"), "❣"),
    EmoteDef(":pixel_heart:", ody("twemoji/symbols/pixel_heart.png"), ":pixel_heart:"),
    EmoteDef(":heart_on_fire:", ody("twemoji/symbols/heart_on_fire.png"), "❤️‍🔥"),
    EmoteDef(":star:", ody("twemoji/symbols/star.png"), "⭐"),
    EmoteDef(":glowing_star:", ody("twemoji/symbols/glowing_star.png"), "🌟"),
    EmoteDef(":sun:", ody("twemoji/symbols/sun.png"), "☀"),
    EmoteDef(":first_quarter_moon_face:", ody("twemoji/symbols/first_quarter_moon_face.png"), "🌛"),
    EmoteDef(":ringed_planet:", ody("twemoji/symbols/ringed_planet.png"), "🪐"),
    EmoteDef(":rainbow:", ody("twemoji/symbols/rainbow.png"), "🌈"),
    EmoteDef(":snowflake:", ody("twemoji/symbols/snowflake.png"), "❄"),
    EmoteDef(":cyclone:", ody("twemoji/symbols/cyclone.png"), "🌀"),
    EmoteDef(":high_voltage:", ody("twemoji/symbols/high_voltage.png"), "⚡"),
    EmoteDef(":fire:", ody("twemoji/symbols/fire.png"), "🔥"),
    EmoteDef(":comet:", ody("twemoji/symbols/comet.png"), "☄"),
    EmoteDef(":recycling:", ody("twemoji/symbols/recycling.png"), "♻"),
    EmoteDef(":hundred_points:", ody("twemoji/symbols/hundred_points.png"), "💯"),
    EmoteDef(":anger_symbol:", ody("twemoji/symbols/anger_symbol.png"), "💢"),
    EmoteDef(":speech_balloon:", ody("twemoji/symbols/speech_balloon.png"), "💬"),
    EmoteDef(":thought_balloon:", ody("twemoji/symbols/thought_balloon.png"), "💭"),
    EmoteDef(":right_anger_bubble:", ody("twemoji/symbols/right_anger_bubble.png"), "🗯"),
    EmoteDef(":zzz:", ody("twemoji/symbols/zzz.png"), "💤"),
    EmoteDef(":collision:", ody("twemoji/symbols/collision.png"), "💥"),
    EmoteDef(":warning:", ody("twemoji/symbols/warning.png"), "⚠"),
    EmoteDef(":no_entry:", ody("twemoji/symbols/no_entry.png"), "⛔"),
    EmoteDef(":prohibited:", ody("twemoji/symbols/prohibited.png"), "🚫"),
    EmoteDef(":kiss_mark:", ody("twemoji/symbols/kiss_mark.png"), "💋"),
)

val TWEMOTES_FOOD = listOf(
    EmoteDef(":grapes:", ody("twemoji/food/grapes.png"), "🍇"),
    EmoteDef(":melon:", ody("twemoji/food/melon.png"), "🍈"),
    EmoteDef(":watermelon:", ody("twemoji/food/watermelon.png"), "🍉"),
    EmoteDef(":tangerine:", ody("twemoji/food/tangerine.png"), "🍊"),
    EmoteDef(":pineapple:", ody("twemoji/food/pineapple.png"), "🍍"),
    EmoteDef(":banana:", ody("twemoji/food/banana.png"), "🍌"),
    EmoteDef(":lemon:", ody("twemoji/food/lemon.png"), "🍋"),
    EmoteDef(":mango:", ody("twemoji/food/mango.png"), "🥭"),
    EmoteDef(":red_apple:", ody("twemoji/food/red_apple.png"), "🍎"),
    EmoteDef(":green_apple:", ody("twemoji/food/green_apple.png"), "🍏"),
    EmoteDef(":pear:", ody("twemoji/food/pear.png"), "🍐"),
    EmoteDef(":peach:", ody("twemoji/food/peach.png"), "🍑"),
    EmoteDef(":cherries:", ody("twemoji/food/cherries.png"), "🍒"),
    EmoteDef(":strawberry:", ody("twemoji/food/strawberry.png"), "🍓"),
    EmoteDef(":blueberries:", ody("twemoji/food/blueberries.png"), "🫐"),
    EmoteDef(":kiwi_fruit:", ody("twemoji/food/kiwi_fruit.png"), "🥝"),
    EmoteDef(":tomato:", ody("twemoji/food/tomato.png"), "🍅"),
    EmoteDef(":olive:", ody("twemoji/food/olive.png"), "🫒"),
    EmoteDef(":coconut:", ody("twemoji/food/coconut.png"), "🥥"),
    EmoteDef(":avocado:", ody("twemoji/food/avocado.png"), "🥑"),
    EmoteDef(":potato:", ody("twemoji/food/potato.png"), "🥔"),
    EmoteDef(":carrot:", ody("twemoji/food/carrot.png"), "🥕"),
    EmoteDef(":ear_of_corn:", ody("twemoji/food/ear_of_corn.png"), "🌽"),
    EmoteDef(":hot_pepper:", ody("twemoji/food/hot_pepper.png"), "🌶"),
    EmoteDef(":bell_pepper:", ody("twemoji/food/bell_pepper.png"), "🫑"),
    EmoteDef(":cucumber:", ody("twemoji/food/cucumber.png"), "🥒"),
    EmoteDef(":leafy_green:", ody("twemoji/food/leafy_green.png"), "🥬"),
    EmoteDef(":broccoli:", ody("twemoji/food/broccoli.png"), "🥦"),
    EmoteDef(":garlic:", ody("twemoji/food/garlic.png"), "🧄"),
    EmoteDef(":onion:", ody("twemoji/food/onion.png"), "🧅"),
    EmoteDef(":peanuts:", ody("twemoji/food/peanuts.png"), "🥜"),
    EmoteDef(":chestnut:", ody("twemoji/food/chestnut.png"), "🌰"),
    EmoteDef(":beans:", ody("twemoji/food/beans.png"), "🫘"),
    EmoteDef(":bread:", ody("twemoji/food/bread.png"), "🍞"),
    EmoteDef(":croissant:", ody("twemoji/food/croissant.png"), "🥐"),
    EmoteDef(":flatbread:", ody("twemoji/food/flatbread.png"), "🫓"),
    EmoteDef(":pretzel:", ody("twemoji/food/pretzel.png"), "🥨"),
    EmoteDef(":bagel:", ody("twemoji/food/bagel.png"), "🥯"),
    EmoteDef(":pancakes:", ody("twemoji/food/pancakes.png"), "🥞"),
    EmoteDef(":waffle:", ody("twemoji/food/waffle.png"), "🧇"),
    EmoteDef(":cheese_wedge:", ody("twemoji/food/cheese_wedge.png"), "🧀"),
    EmoteDef(":meat_on_bone:", ody("twemoji/food/meat_on_bone.png"), "🍖"),
    EmoteDef(":poultry_leg:", ody("twemoji/food/poultry_leg.png"), "🍗"),
    EmoteDef(":cut_of_meat:", ody("twemoji/food/cut_of_meat.png"), "🥩"),
    EmoteDef(":bacon:", ody("twemoji/food/bacon.png"), "🥓"),
    EmoteDef(":hamburger:", ody("twemoji/food/hamburger.png"), "🍔"),
    EmoteDef(":french_fries:", ody("twemoji/food/french_fries.png"), "🍟"),
    EmoteDef(":pizza:", ody("twemoji/food/pizza.png"), "🍕"),
    EmoteDef(":hot_dog:", ody("twemoji/food/hot_dog.png"), "🌭"),
    EmoteDef(":sandwich:", ody("twemoji/food/sandwich.png"), "🥪"),
    EmoteDef(":taco:", ody("twemoji/food/taco.png"), "🌮"),
    EmoteDef(":burrito:", ody("twemoji/food/burrito.png"), "🌯"),
    EmoteDef(":tamale:", ody("twemoji/food/tamale.png"), "🫔"),
    EmoteDef(":stuffed_flatbread:", ody("twemoji/food/stuffed_flatbread.png"), "🥙"),
    EmoteDef(":falafel:", ody("twemoji/food/falafel.png"), "🧆"),
    EmoteDef(":egg:", ody("twemoji/food/egg.png"), "🥚"),
    EmoteDef(":cooking:", ody("twemoji/food/cooking.png"), "🍳"),
    EmoteDef(":shallow_pan_of_food:", ody("twemoji/food/shallow_pan_of_food.png"), "🥘"),
    EmoteDef(":pot_of_food:", ody("twemoji/food/pot_of_food.png"), "🍲"),
    EmoteDef(":fondue:", ody("twemoji/food/fondue.png"), "🫕"),
    EmoteDef(":bowl_with_spoon:", ody("twemoji/food/bowl_with_spoon.png"), "🥣"),
    EmoteDef(":green_salad:", ody("twemoji/food/green_salad.png"), "🥗"),
    EmoteDef(":popcorn:", ody("twemoji/food/popcorn.png"), "🍿"),
    EmoteDef(":butter:", ody("twemoji/food/butter.png"), "🧈"),
    EmoteDef(":salt:", ody("twemoji/food/salt.png"), "🧂"),
    EmoteDef(":bento_box:", ody("twemoji/food/bento_box.png"), "🍱"),
    EmoteDef(":rice_cracker:", ody("twemoji/food/rice_cracker.png"), "🍘"),
    EmoteDef(":rice_ball:", ody("twemoji/food/rice_ball.png"), "🍙"),
    EmoteDef(":cooked_rice:", ody("twemoji/food/cooked_rice.png"), "🍚"),
    EmoteDef(":curry_rice:", ody("twemoji/food/curry_rice.png"), "🍛"),
    EmoteDef(":steaming_bowl:", ody("twemoji/food/steaming_bowl.png"), "🍜"),
    EmoteDef(":spaghetti:", ody("twemoji/food/spaghetti.png"), "🍝"),
    EmoteDef(":roasted_sweet_potato:", ody("twemoji/food/roasted_sweet_potato.png"), "🍠"),
    EmoteDef(":oden:", ody("twemoji/food/oden.png"), "🍢"),
    EmoteDef(":sushi:", ody("twemoji/food/sushi.png"), "🍣"),
    EmoteDef(":fried_shrimp:", ody("twemoji/food/fried_shrimp.png"), "🍤"),
    EmoteDef(":fish_cake_with_swirl:", ody("twemoji/food/fish_cake_with_swirl.png"), "🍥"),
    EmoteDef(":moon_cake:", ody("twemoji/food/moon_cake.png"), "🥮"),
    EmoteDef(":dango:", ody("twemoji/food/dango.png"), "🍡"),
    EmoteDef(":dumpling:", ody("twemoji/food/dumpling.png"), "🥟"),
    EmoteDef(":fortune_cookie:", ody("twemoji/food/fortune_cookie.png"), "🥠"),
    EmoteDef(":soft_ice_cream:", ody("twemoji/food/soft_ice_cream.png"), "🍦"),
    EmoteDef(":shaved_ice:", ody("twemoji/food/shaved_ice.png"), "🍧"),
    EmoteDef(":ice_cream:", ody("twemoji/food/ice_cream.png"), "🍨"),
    EmoteDef(":doughnut:", ody("twemoji/food/doughnut.png"), "🍩"),
    EmoteDef(":cookie:", ody("twemoji/food/cookie.png"), "🍪"),
    EmoteDef(":birthday_cake:", ody("twemoji/food/birthday_cake.png"), "🎂"),
    EmoteDef(":shortcake:", ody("twemoji/food/shortcake.png"), "🍰"),
    EmoteDef(":cupcake:", ody("twemoji/food/cupcake.png"), "🧁"),
    EmoteDef(":pie:", ody("twemoji/food/pie.png"), "🥧"),
    EmoteDef(":chocolate_bar:", ody("twemoji/food/chocolate_bar.png"), "🍫"),
    EmoteDef(":lollipop:", ody("twemoji/food/lollipop.png"), "🍭"),
    EmoteDef(":custard:", ody("twemoji/food/custard.png"), "🍮"),
    EmoteDef(":baby_bottle:", ody("twemoji/food/baby_bottle.png"), "🍼"),
    EmoteDef(":glass_of_milk:", ody("twemoji/food/glass_of_milk.png"), "🥛"),
    EmoteDef(":hot_beverage:", ody("twemoji/food/hot_beverage.png"), "☕"),
    EmoteDef(":teacup_without_handle:", ody("twemoji/food/teacup_without_handle.png"), "🍵"),
    EmoteDef(":sake:", ody("twemoji/food/sake.png"), "🍶"),
    EmoteDef(":bottle_with_popping_cork:", ody("twemoji/food/bottle_with_popping_cork.png"), "🍾"),
    EmoteDef(":wine_glass:", ody("twemoji/food/wine_glass.png"), "🍷"),
    EmoteDef(":cocktail_glass:", ody("twemoji/food/cocktail_glass.png"), "🍸"),
    EmoteDef(":tropical_drink:", ody("twemoji/food/tropical_drink.png"), "🍹"),
    EmoteDef(":beer_mug:", ody("twemoji/food/beer_mug.png"), "🍺"),
    EmoteDef(":clinking_beer_mugs:", ody("twemoji/food/clinking_beer_mugs.png"), "🍻"),
    EmoteDef(":clinking_glasses:", ody("twemoji/food/clinking_glasses.png"), "🥂"),
    EmoteDef(":tumbler_glass:", ody("twemoji/food/tumbler_glass.png"), "🥃"),
    EmoteDef(":cup_with_straw:", ody("twemoji/food/cup_with_straw.png"), "🥤"),
    EmoteDef(":bubble_tea:", ody("twemoji/food/bubble_tea.png"), "🧋"),
    EmoteDef(":beverage_box:", ody("twemoji/food/beverage_box.png"), "🧃"),
    EmoteDef(":mate:", ody("twemoji/food/mate.png"), "🧉"),
    EmoteDef(":fork_and_knife:", ody("twemoji/food/fork_and_knife.png"), "🍴"),
    EmoteDef(":chopsticks:", ody("twemoji/food/chopsticks.png"), "🥢"),
)

val TWEMOTES_FLAGS = listOf(
    EmoteDef(":flag_ascension_island:", ody("twemoji/flags/flag_ascension_island.png"), "🇦🇨"),
    EmoteDef(":flag_andorra:", ody("twemoji/flags/flag_andorra.png"), "🇦🇩"),
    EmoteDef(":flag_united_arab_emirates:", ody("twemoji/flags/flag_united_arab_emirates.png"), "🇦🇪"),
    EmoteDef(":flag_afghanistan:", ody("twemoji/flags/flag_afghanistan.png"), "🇦🇫"),
    EmoteDef(":flag_antigua_barbuda:", ody("twemoji/flags/flag_antigua_barbuda.png"), "🇦🇬"),
    EmoteDef(":flag_anguilla:", ody("twemoji/flags/flag_anguilla.png"), "🇦🇮"),
    EmoteDef(":flag_albania:", ody("twemoji/flags/flag_albania.png"), "🇦🇱"),
    EmoteDef(":flag_armenia:", ody("twemoji/flags/flag_armenia.png"), "🇦🇲"),
    EmoteDef(":flag_angola:", ody("twemoji/flags/flag_angola.png"), "🇦🇴"),
    EmoteDef(":flag_antarctica:", ody("twemoji/flags/flag_antarctica.png"), "🇦🇶"),
    EmoteDef(":flag_argentina:", ody("twemoji/flags/flag_argentina.png"), "🇦🇷"),
    EmoteDef(":flag_american_samoa:", ody("twemoji/flags/flag_american_samoa.png"), "🇦🇸"),
    EmoteDef(":flag_austria:", ody("twemoji/flags/flag_austria.png"), "🇦🇹"),
    EmoteDef(":flag_australia:", ody("twemoji/flags/flag_australia.png"), "🇦🇺"),
    EmoteDef(":flag_aruba:", ody("twemoji/flags/flag_aruba.png"), "🇦🇼"),
    EmoteDef(":flag_aland_islands:", ody("twemoji/flags/flag_aland_islands.png"), "🇦🇽"),
    EmoteDef(":flag_azerbaijan:", ody("twemoji/flags/flag_azerbaijan.png"), "🇦🇿"),
    EmoteDef(":flag_bosnia_herzegovina:", ody("twemoji/flags/flag_bosnia_herzegovina.png"), "🇧🇦"),
    EmoteDef(":flag_barbados:", ody("twemoji/flags/flag_barbados.png"), "🇧🇧"),
    EmoteDef(":flag_bangladesh:", ody("twemoji/flags/flag_bangladesh.png"), "🇧🇩"),
    EmoteDef(":flag_belgium:", ody("twemoji/flags/flag_belgium.png"), "🇧🇪"),
    EmoteDef(":flag_burkina_faso:", ody("twemoji/flags/flag_burkina_faso.png"), "🇧🇫"),
    EmoteDef(":flag_bulgaria:", ody("twemoji/flags/flag_bulgaria.png"), "🇧🇬"),
    EmoteDef(":flag_bahrain:", ody("twemoji/flags/flag_bahrain.png"), "🇧🇭"),
    EmoteDef(":flag_burundi:", ody("twemoji/flags/flag_burundi.png"), "🇧🇮"),
    EmoteDef(":flag_benin:", ody("twemoji/flags/flag_benin.png"), "🇧🇯"),
    EmoteDef(":flag_st_barthelemy:", ody("twemoji/flags/flag_st_barthelemy.png"), "🇧🇱"),
    EmoteDef(":flag_bermuda:", ody("twemoji/flags/flag_bermuda.png"), "🇧🇲"),
    EmoteDef(":flag_brunei:", ody("twemoji/flags/flag_brunei.png"), "🇧🇳"),
    EmoteDef(":flag_bolivia:", ody("twemoji/flags/flag_bolivia.png"), "🇧🇴"),
    EmoteDef(":flag_caribbean_netherlands:", ody("twemoji/flags/flag_caribbean_netherlands.png"), "🇧🇶"),
    EmoteDef(":flag_brazil:", ody("twemoji/flags/flag_brazil.png"), "🇧🇷"),
    EmoteDef(":flag_bahamas:", ody("twemoji/flags/flag_bahamas.png"), "🇧🇸"),
    EmoteDef(":flag_bhutan:", ody("twemoji/flags/flag_bhutan.png"), "🇧🇹"),
    EmoteDef(":flag_bouvet_island:", ody("twemoji/flags/flag_bouvet_island.png"), "🇧🇻"),
    EmoteDef(":flag_botswana:", ody("twemoji/flags/flag_botswana.png"), "🇧🇼"),
    EmoteDef(":flag_belarus:", ody("twemoji/flags/flag_belarus.png"), "🇧🇾"),
    EmoteDef(":flag_belize:", ody("twemoji/flags/flag_belize.png"), "🇧🇿"),
    EmoteDef(":flag_canada:", ody("twemoji/flags/flag_canada.png"), "🇨🇦"),
    EmoteDef(":flag_cocos_keeling_islands:", ody("twemoji/flags/flag_cocos_keeling_islands.png"), "🇨🇨"),
    EmoteDef(":flag_congo_kinshasa:", ody("twemoji/flags/flag_congo_kinshasa.png"), "🇨🇩"),
    EmoteDef(":flag_central_african_republic:", ody("twemoji/flags/flag_central_african_republic.png"), "🇨🇫"),
    EmoteDef(":flag_congo_brazzaville:", ody("twemoji/flags/flag_congo_brazzaville.png"), "🇨🇬"),
    EmoteDef(":flag_switzerland:", ody("twemoji/flags/flag_switzerland.png"), "🇨🇭"),
    EmoteDef(":flag_cote_divoire:", ody("twemoji/flags/flag_cote_divoire.png"), "🇨🇮"),
    EmoteDef(":flag_cook_islands:", ody("twemoji/flags/flag_cook_islands.png"), "🇨🇰"),
    EmoteDef(":flag_chile:", ody("twemoji/flags/flag_chile.png"), "🇨🇱"),
    EmoteDef(":flag_cameroon:", ody("twemoji/flags/flag_cameroon.png"), "🇨🇲"),
    EmoteDef(":flag_china:", ody("twemoji/flags/flag_china.png"), "🇨🇳"),
    EmoteDef(":flag_colombia:", ody("twemoji/flags/flag_colombia.png"), "🇨🇴"),
    EmoteDef(":flag_clipperton_island:", ody("twemoji/flags/flag_clipperton_island.png"), "🇨🇵"),
    EmoteDef(":flag_costa_rica:", ody("twemoji/flags/flag_costa_rica.png"), "🇨🇷"),
    EmoteDef(":flag_cuba:", ody("twemoji/flags/flag_cuba.png"), "🇨🇺"),
    EmoteDef(":flag_cape_verde:", ody("twemoji/flags/flag_cape_verde.png"), "🇨🇻"),
    EmoteDef(":flag_curacao:", ody("twemoji/flags/flag_curacao.png"), "🇨🇼"),
    EmoteDef(":flag_christmas_island:", ody("twemoji/flags/flag_christmas_island.png"), "🇨🇽"),
    EmoteDef(":flag_cyprus:", ody("twemoji/flags/flag_cyprus.png"), "🇨🇾"),
    EmoteDef(":flag_czechia:", ody("twemoji/flags/flag_czechia.png"), "🇨🇿"),
    EmoteDef(":flag_germany:", ody("twemoji/flags/flag_germany.png"), "🇩🇪"),
    EmoteDef(":flag_diego_garcia:", ody("twemoji/flags/flag_diego_garcia.png"), "🇩🇬"),
    EmoteDef(":flag_djibouti:", ody("twemoji/flags/flag_djibouti.png"), "🇩🇯"),
    EmoteDef(":flag_denmark:", ody("twemoji/flags/flag_denmark.png"), "🇩🇰"),
    EmoteDef(":flag_dominica:", ody("twemoji/flags/flag_dominica.png"), "🇩🇲"),
    EmoteDef(":flag_dominican_republic:", ody("twemoji/flags/flag_dominican_republic.png"), "🇩🇴"),
    EmoteDef(":flag_algeria:", ody("twemoji/flags/flag_algeria.png"), "🇩🇿"),
    EmoteDef(":flag_ceuta_melilla:", ody("twemoji/flags/flag_ceuta_melilla.png"), "🇪🇦"),
    EmoteDef(":flag_ecuador:", ody("twemoji/flags/flag_ecuador.png"), "🇪🇨"),
    EmoteDef(":flag_estonia:", ody("twemoji/flags/flag_estonia.png"), "🇪🇪"),
    EmoteDef(":flag_egypt:", ody("twemoji/flags/flag_egypt.png"), "🇪🇬"),
    EmoteDef(":flag_western_sahara:", ody("twemoji/flags/flag_western_sahara.png"), "🇪🇭"),
    EmoteDef(":flag_eritrea:", ody("twemoji/flags/flag_eritrea.png"), "🇪🇷"),
    EmoteDef(":flag_spain:", ody("twemoji/flags/flag_spain.png"), "🇪🇸"),
    EmoteDef(":flag_ethiopia:", ody("twemoji/flags/flag_ethiopia.png"), "🇪🇹"),
    EmoteDef(":flag_finland:", ody("twemoji/flags/flag_finland.png"), "🇫🇮"),
    EmoteDef(":flag_fiji:", ody("twemoji/flags/flag_fiji.png"), "🇫🇯"),
    EmoteDef(":flag_falkland_islands:", ody("twemoji/flags/flag_falkland_islands.png"), "🇫🇰"),
    EmoteDef(":flag_micronesia:", ody("twemoji/flags/flag_micronesia.png"), "🇫🇲"),
    EmoteDef(":flag_faroe_islands:", ody("twemoji/flags/flag_faroe_islands.png"), "🇫🇴"),
    EmoteDef(":flag_france:", ody("twemoji/flags/flag_france.png"), "🇫🇷"),
    EmoteDef(":flag_gabon:", ody("twemoji/flags/flag_gabon.png"), "🇬🇦"),
    EmoteDef(":flag_united_kingdom:", ody("twemoji/flags/flag_united_kingdom.png"), "🇬🇧"),
    EmoteDef(":flag_grenada:", ody("twemoji/flags/flag_grenada.png"), "🇬🇩"),
    EmoteDef(":flag_georgia:", ody("twemoji/flags/flag_georgia.png"), "🇬🇪"),
    EmoteDef(":flag_french_guiana:", ody("twemoji/flags/flag_french_guiana.png"), "🇬🇫"),
    EmoteDef(":flag_guernsey:", ody("twemoji/flags/flag_guernsey.png"), "🇬🇬"),
    EmoteDef(":flag_ghana:", ody("twemoji/flags/flag_ghana.png"), "🇬🇭"),
    EmoteDef(":flag_gibraltar:", ody("twemoji/flags/flag_gibraltar.png"), "🇬🇮"),
    EmoteDef(":flag_greenland:", ody("twemoji/flags/flag_greenland.png"), "🇬🇱"),
    EmoteDef(":flag_gambia:", ody("twemoji/flags/flag_gambia.png"), "🇬🇲"),
    EmoteDef(":flag_guinea:", ody("twemoji/flags/flag_guinea.png"), "🇬🇳"),
    EmoteDef(":flag_guadeloupe:", ody("twemoji/flags/flag_guadeloupe.png"), "🇬🇵"),
    EmoteDef(":flag_equatorial_guinea:", ody("twemoji/flags/flag_equatorial_guinea.png"), "🇬🇶"),
    EmoteDef(":flag_greece:", ody("twemoji/flags/flag_greece.png"), "🇬🇷"),
    EmoteDef(":flag_guatemala:", ody("twemoji/flags/flag_guatemala.png"), "🇬🇹"),
    EmoteDef(":flag_guam:", ody("twemoji/flags/flag_guam.png"), "🇬🇺"),
    EmoteDef(":flag_guinea_bissau:", ody("twemoji/flags/flag_guinea_bissau.png"), "🇬🇼"),
    EmoteDef(":flag_guyana:", ody("twemoji/flags/flag_guyana.png"), "🇬🇾"),
    EmoteDef(":flag_hong_kong_sar_china:", ody("twemoji/flags/flag_hong_kong_sar_china.png"), "🇭🇰"),
    EmoteDef(":flag_heard_mcdonald_islands:", ody("twemoji/flags/flag_heard_mcdonald_islands.png"), "🇭🇲"),
    EmoteDef(":flag_honduras:", ody("twemoji/flags/flag_honduras.png"), "🇭🇳"),
    EmoteDef(":flag_croatia:", ody("twemoji/flags/flag_croatia.png"), "🇭🇷"),
    EmoteDef(":flag_haiti:", ody("twemoji/flags/flag_haiti.png"), "🇭🇹"),
    EmoteDef(":flag_hungary:", ody("twemoji/flags/flag_hungary.png"), "🇭🇺"),
    EmoteDef(":flag_canary_islands:", ody("twemoji/flags/flag_canary_islands.png"), "🇮🇨"),
    EmoteDef(":flag_indonesia:", ody("twemoji/flags/flag_indonesia.png"), "🇮🇩"),
    EmoteDef(":flag_ireland:", ody("twemoji/flags/flag_ireland.png"), "🇮🇪"),
    EmoteDef(":flag_israel:", ody("twemoji/flags/flag_israel.png"), "🇮🇱"),
    EmoteDef(":flag_isle_of_man:", ody("twemoji/flags/flag_isle_of_man.png"), "🇮🇲"),
    EmoteDef(":flag_india:", ody("twemoji/flags/flag_india.png"), "🇮🇳"),
    EmoteDef(":flag_british_indian_ocean_territory:", ody("twemoji/flags/flag_british_indian_ocean_territory.png"), "🇮🇴"),
    EmoteDef(":flag_iraq:", ody("twemoji/flags/flag_iraq.png"), "🇮🇶"),
    EmoteDef(":flag_iran:", ody("twemoji/flags/flag_iran.png"), "🇮🇷"),
    EmoteDef(":flag_iceland:", ody("twemoji/flags/flag_iceland.png"), "🇮🇸"),
    EmoteDef(":flag_italy:", ody("twemoji/flags/flag_italy.png"), "🇮🇹"),
    EmoteDef(":flag_jersey:", ody("twemoji/flags/flag_jersey.png"), "🇯🇪"),
    EmoteDef(":flag_jamaica:", ody("twemoji/flags/flag_jamaica.png"), "🇯🇲"),
    EmoteDef(":flag_jordan:", ody("twemoji/flags/flag_jordan.png"), "🇯🇴"),
    EmoteDef(":flag_japan:", ody("twemoji/flags/flag_japan.png"), "🇯🇵"),
    EmoteDef(":flag_kenya:", ody("twemoji/flags/flag_kenya.png"), "🇰🇪"),
    EmoteDef(":flag_kyrgyzstan:", ody("twemoji/flags/flag_kyrgyzstan.png"), "🇰🇬"),
    EmoteDef(":flag_cambodia:", ody("twemoji/flags/flag_cambodia.png"), "🇰🇭"),
    EmoteDef(":flag_kiribati:", ody("twemoji/flags/flag_kiribati.png"), "🇰🇮"),
    EmoteDef(":flag_comoros:", ody("twemoji/flags/flag_comoros.png"), "🇰🇲"),
    EmoteDef(":flag_st_kitts_nevis:", ody("twemoji/flags/flag_st_kitts_nevis.png"), "🇰🇳"),
    EmoteDef(":flag_north_korea:", ody("twemoji/flags/flag_north_korea.png"), "🇰🇵"),
    EmoteDef(":flag_south_korea:", ody("twemoji/flags/flag_south_korea.png"), "🇰🇷"),
    EmoteDef(":flag_kuwait:", ody("twemoji/flags/flag_kuwait.png"), "🇰🇼"),
    EmoteDef(":flag_cayman_islands:", ody("twemoji/flags/flag_cayman_islands.png"), "🇰🇾"),
    EmoteDef(":flag_kazakhstan:", ody("twemoji/flags/flag_kazakhstan.png"), "🇰🇿"),
    EmoteDef(":flag_laos:", ody("twemoji/flags/flag_laos.png"), "🇱🇦"),
    EmoteDef(":flag_lebanon:", ody("twemoji/flags/flag_lebanon.png"), "🇱🇧"),
    EmoteDef(":flag_st_lucia:", ody("twemoji/flags/flag_st_lucia.png"), "🇱🇨"),
    EmoteDef(":flag_liechtenstein:", ody("twemoji/flags/flag_liechtenstein.png"), "🇱🇮"),
    EmoteDef(":flag_sri_lanka:", ody("twemoji/flags/flag_sri_lanka.png"), "🇱🇰"),
    EmoteDef(":flag_liberia:", ody("twemoji/flags/flag_liberia.png"), "🇱🇷"),
    EmoteDef(":flag_lesotho:", ody("twemoji/flags/flag_lesotho.png"), "🇱🇸"),
    EmoteDef(":flag_lithuania:", ody("twemoji/flags/flag_lithuania.png"), "🇱🇹"),
    EmoteDef(":flag_luxembourg:", ody("twemoji/flags/flag_luxembourg.png"), "🇱🇺"),
    EmoteDef(":flag_latvia:", ody("twemoji/flags/flag_latvia.png"), "🇱🇻"),
    EmoteDef(":flag_libya:", ody("twemoji/flags/flag_libya.png"), "🇱🇾"),
    EmoteDef(":flag_morocco:", ody("twemoji/flags/flag_morocco.png"), "🇲🇦"),
    EmoteDef(":flag_monaco:", ody("twemoji/flags/flag_monaco.png"), "🇲🇨"),
    EmoteDef(":flag_moldova:", ody("twemoji/flags/flag_moldova.png"), "🇲🇩"),
    EmoteDef(":flag_montenegro:", ody("twemoji/flags/flag_montenegro.png"), "🇲🇪"),
    EmoteDef(":flag_st_martin:", ody("twemoji/flags/flag_st_martin.png"), "🇲🇫"),
    EmoteDef(":flag_madagascar:", ody("twemoji/flags/flag_madagascar.png"), "🇲🇬"),
    EmoteDef(":flag_marshall_islands:", ody("twemoji/flags/flag_marshall_islands.png"), "🇲🇭"),
    EmoteDef(":flag_north_macedonia:", ody("twemoji/flags/flag_north_macedonia.png"), "🇲🇰"),
    EmoteDef(":flag_mali:", ody("twemoji/flags/flag_mali.png"), "🇲🇱"),
    EmoteDef(":flag_myanmar_burma:", ody("twemoji/flags/flag_myanmar_burma.png"), "🇲🇲"),
    EmoteDef(":flag_mongolia:", ody("twemoji/flags/flag_mongolia.png"), "🇲🇳"),
    EmoteDef(":flag_macao_sar_china:", ody("twemoji/flags/flag_macao_sar_china.png"), "🇲🇴"),
    EmoteDef(":flag_northern_mariana_islands:", ody("twemoji/flags/flag_northern_mariana_islands.png"), "🇲🇵"),
    EmoteDef(":flag_martinique:", ody("twemoji/flags/flag_martinique.png"), "🇲🇶"),
    EmoteDef(":flag_mauritania:", ody("twemoji/flags/flag_mauritania.png"), "🇲🇷"),
    EmoteDef(":flag_montserrat:", ody("twemoji/flags/flag_montserrat.png"), "🇲🇸"),
    EmoteDef(":flag_malta:", ody("twemoji/flags/flag_malta.png"), "🇲🇹"),
    EmoteDef(":flag_mauritius:", ody("twemoji/flags/flag_mauritius.png"), "🇲🇺"),
    EmoteDef(":flag_maldives:", ody("twemoji/flags/flag_maldives.png"), "🇲🇻"),
    EmoteDef(":flag_malawi:", ody("twemoji/flags/flag_malawi.png"), "🇲🇼"),
    EmoteDef(":flag_mexico:", ody("twemoji/flags/flag_mexico.png"), "🇲🇽"),
    EmoteDef(":flag_malaysia:", ody("twemoji/flags/flag_malaysia.png"), "🇲🇾"),
    EmoteDef(":flag_mozambique:", ody("twemoji/flags/flag_mozambique.png"), "🇲🇿"),
    EmoteDef(":flag_namibia:", ody("twemoji/flags/flag_namibia.png"), "🇳🇦"),
    EmoteDef(":flag_new_caledonia:", ody("twemoji/flags/flag_new_caledonia.png"), "🇳🇨"),
    EmoteDef(":flag_niger:", ody("twemoji/flags/flag_niger.png"), "🇳🇪"),
    EmoteDef(":flag_norfolk_island:", ody("twemoji/flags/flag_norfolk_island.png"), "🇳🇫"),
    EmoteDef(":flag_nigeria:", ody("twemoji/flags/flag_nigeria.png"), "🇳🇬"),
    EmoteDef(":flag_nicaragua:", ody("twemoji/flags/flag_nicaragua.png"), "🇳🇮"),
    EmoteDef(":flag_netherlands:", ody("twemoji/flags/flag_netherlands.png"), "🇳🇱"),
    EmoteDef(":flag_norway:", ody("twemoji/flags/flag_norway.png"), "🇳🇴"),
    EmoteDef(":flag_nepal:", ody("twemoji/flags/flag_nepal.png"), "🇳🇵"),
    EmoteDef(":flag_nauru:", ody("twemoji/flags/flag_nauru.png"), "🇳🇷"),
    EmoteDef(":flag_niue:", ody("twemoji/flags/flag_niue.png"), "🇳🇺"),
    EmoteDef(":flag_new_zealand:", ody("twemoji/flags/flag_new_zealand.png"), "🇳🇿"),
    EmoteDef(":flag_oman:", ody("twemoji/flags/flag_oman.png"), "🇴🇲"),
    EmoteDef(":flag_panama:", ody("twemoji/flags/flag_panama.png"), "🇵🇦"),
    EmoteDef(":flag_peru:", ody("twemoji/flags/flag_peru.png"), "🇵🇪"),
    EmoteDef(":flag_french_polynesia:", ody("twemoji/flags/flag_french_polynesia.png"), "🇵🇫"),
    EmoteDef(":flag_papua_new_guinea:", ody("twemoji/flags/flag_papua_new_guinea.png"), "🇵🇬"),
    EmoteDef(":flag_philippines:", ody("twemoji/flags/flag_philippines.png"), "🇵🇭"),
    EmoteDef(":flag_pakistan:", ody("twemoji/flags/flag_pakistan.png"), "🇵🇰"),
    EmoteDef(":flag_poland:", ody("twemoji/flags/flag_poland.png"), "🇵🇱"),
    EmoteDef(":flag_st_pierre_miquelon:", ody("twemoji/flags/flag_st_pierre_miquelon.png"), "🇵🇲"),
    EmoteDef(":flag_pitcairn_islands:", ody("twemoji/flags/flag_pitcairn_islands.png"), "🇵🇳"),
    EmoteDef(":flag_puerto_rico:", ody("twemoji/flags/flag_puerto_rico.png"), "🇵🇷"),
    EmoteDef(":flag_palestinian_territories:", ody("twemoji/flags/flag_palestinian_territories.png"), "🇵🇸"),
    EmoteDef(":flag_portugal:", ody("twemoji/flags/flag_portugal.png"), "🇵🇹"),
    EmoteDef(":flag_palau:", ody("twemoji/flags/flag_palau.png"), "🇵🇼"),
    EmoteDef(":flag_paraguay:", ody("twemoji/flags/flag_paraguay.png"), "🇵🇾"),
    EmoteDef(":flag_qatar:", ody("twemoji/flags/flag_qatar.png"), "🇶🇦"),
    EmoteDef(":flag_reunion:", ody("twemoji/flags/flag_reunion.png"), "🇷🇪"),
    EmoteDef(":flag_romania:", ody("twemoji/flags/flag_romania.png"), "🇷🇴"),
    EmoteDef(":flag_serbia:", ody("twemoji/flags/flag_serbia.png"), "🇷🇸"),
    EmoteDef(":flag_russia:", ody("twemoji/flags/flag_russia.png"), "🇷🇺"),
    EmoteDef(":flag_rwanda:", ody("twemoji/flags/flag_rwanda.png"), "🇷🇼"),
    EmoteDef(":flag_saudi_arabia:", ody("twemoji/flags/flag_saudi_arabia.png"), "🇸🇦"),
    EmoteDef(":flag_solomon_islands:", ody("twemoji/flags/flag_solomon_islands.png"), "🇸🇧"),
    EmoteDef(":flag_seychelles:", ody("twemoji/flags/flag_seychelles.png"), "🇸🇨"),
    EmoteDef(":flag_sudan:", ody("twemoji/flags/flag_sudan.png"), "🇸🇩"),
    EmoteDef(":flag_sweden:", ody("twemoji/flags/flag_sweden.png"), "🇸🇪"),
    EmoteDef(":flag_singapore:", ody("twemoji/flags/flag_singapore.png"), "🇸🇬"),
    EmoteDef(":flag_st_helena:", ody("twemoji/flags/flag_st_helena.png"), "🇸🇭"),
    EmoteDef(":flag_slovenia:", ody("twemoji/flags/flag_slovenia.png"), "🇸🇮"),
    EmoteDef(":flag_svalbard_jan_mayen:", ody("twemoji/flags/flag_svalbard_jan_mayen.png"), "🇸🇯"),
    EmoteDef(":flag_slovakia:", ody("twemoji/flags/flag_slovakia.png"), "🇸🇰"),
    EmoteDef(":flag_sierra_leone:", ody("twemoji/flags/flag_sierra_leone.png"), "🇸🇱"),
    EmoteDef(":flag_san_marino:", ody("twemoji/flags/flag_san_marino.png"), "🇸🇲"),
    EmoteDef(":flag_senegal:", ody("twemoji/flags/flag_senegal.png"), "🇸🇳"),
    EmoteDef(":flag_somalia:", ody("twemoji/flags/flag_somalia.png"), "🇸🇴"),
    EmoteDef(":flag_suriname:", ody("twemoji/flags/flag_suriname.png"), "🇸🇷"),
    EmoteDef(":flag_south_sudan:", ody("twemoji/flags/flag_south_sudan.png"), "🇸🇸"),
    EmoteDef(":flag_sao_tome_principe:", ody("twemoji/flags/flag_sao_tome_principe.png"), "🇸🇹"),
    EmoteDef(":flag_el_salvador:", ody("twemoji/flags/flag_el_salvador.png"), "🇸🇻"),
    EmoteDef(":flag_sint_maarten:", ody("twemoji/flags/flag_sint_maarten.png"), "🇸🇽"),
    EmoteDef(":flag_syria:", ody("twemoji/flags/flag_syria.png"), "🇸🇾"),
    EmoteDef(":flag_eswatini:", ody("twemoji/flags/flag_eswatini.png"), "🇸🇿"),
    EmoteDef(":flag_tristan_da_cunha:", ody("twemoji/flags/flag_tristan_da_cunha.png"), "🇹🇦"),
    EmoteDef(":flag_turks_caicos_islands:", ody("twemoji/flags/flag_turks_caicos_islands.png"), "🇹🇨"),
    EmoteDef(":flag_chad:", ody("twemoji/flags/flag_chad.png"), "🇹🇩"),
    EmoteDef(":flag_french_southern_territories:", ody("twemoji/flags/flag_french_southern_territories.png"), "🇹🇫"),
    EmoteDef(":flag_togo:", ody("twemoji/flags/flag_togo.png"), "🇹🇬"),
    EmoteDef(":flag_thailand:", ody("twemoji/flags/flag_thailand.png"), "🇹🇭"),
    EmoteDef(":flag_tajikistan:", ody("twemoji/flags/flag_tajikistan.png"), "🇹🇯"),
    EmoteDef(":flag_tokelau:", ody("twemoji/flags/flag_tokelau.png"), "🇹🇰"),
    EmoteDef(":flag_tibet:", ody("twemoji/flags/flag_tibet.png"), "🏴󠁣󠁮󠀵󠀴󠁿"),
    EmoteDef(":flag_timor_leste:", ody("twemoji/flags/flag_timor_leste.png"), "🇹🇱"),
    EmoteDef(":flag_turkmenistan:", ody("twemoji/flags/flag_turkmenistan.png"), "🇹🇲"),
    EmoteDef(":flag_tunisia:", ody("twemoji/flags/flag_tunisia.png"), "🇹🇳"),
    EmoteDef(":flag_tonga:", ody("twemoji/flags/flag_tonga.png"), "🇹🇴"),
    EmoteDef(":flag_turkey:", ody("twemoji/flags/flag_turkey.png"), "🇹🇷"),
    EmoteDef(":flag_trinidad_tobago:", ody("twemoji/flags/flag_trinidad_tobago.png"), "🇹🇹"),
    EmoteDef(":flag_tuvalu:", ody("twemoji/flags/flag_tuvalu.png"), "🇹🇻"),
    EmoteDef(":flag_taiwan:", ody("twemoji/flags/flag_taiwan.png"), "🇹🇼"),
    EmoteDef(":flag_tanzania:", ody("twemoji/flags/flag_tanzania.png"), "🇹🇿"),
    EmoteDef(":flag_ukraine:", ody("twemoji/flags/flag_ukraine.png"), "🇺🇦"),
    EmoteDef(":flag_uganda:", ody("twemoji/flags/flag_uganda.png"), "🇺🇬"),
    EmoteDef(":flag_united_states:", ody("twemoji/flags/flag_united_states.png"), "🇺🇸"),
    EmoteDef(":flag_uruguay:", ody("twemoji/flags/flag_uruguay.png"), "🇺🇾"),
    EmoteDef(":flag_uzbekistan:", ody("twemoji/flags/flag_uzbekistan.png"), "🇺🇿"),
    EmoteDef(":flag_vatican_city:", ody("twemoji/flags/flag_vatican_city.png"), "🇻🇦"),
    EmoteDef(":flag_st_vincent_grenadines:", ody("twemoji/flags/flag_st_vincent_grenadines.png"), "🇻🇨"),
    EmoteDef(":flag_venezuela:", ody("twemoji/flags/flag_venezuela.png"), "🇻🇪"),
    EmoteDef(":flag_british_virgin_islands:", ody("twemoji/flags/flag_british_virgin_islands.png"), "🇻🇬"),
    EmoteDef(":flag_us_virgin_islands:", ody("twemoji/flags/flag_us_virgin_islands.png"), "🇻🇮"),
    EmoteDef(":flag_vietnam:", ody("twemoji/flags/flag_vietnam.png"), "🇻🇳"),
    EmoteDef(":flag_vanuatu:", ody("twemoji/flags/flag_vanuatu.png"), "🇻🇺"),
    EmoteDef(":flag_wallis_futuna:", ody("twemoji/flags/flag_wallis_futuna.png"), "🇼🇫"),
    EmoteDef(":flag_samoa:", ody("twemoji/flags/flag_samoa.png"), "🇼🇸"),
    EmoteDef(":flag_kosovo:", ody("twemoji/flags/flag_kosovo.png"), "🇽🇰"),
    EmoteDef(":flag_yemen:", ody("twemoji/flags/flag_yemen.png"), "🇾🇪"),
    EmoteDef(":flag_mayotte:", ody("twemoji/flags/flag_mayotte.png"), "🇾🇹"),
    EmoteDef(":flag_south_africa:", ody("twemoji/flags/flag_south_africa.png"), "🇿🇦"),
    EmoteDef(":flag_zambia:", ody("twemoji/flags/flag_zambia.png"), "🇿🇲"),
    EmoteDef(":flag_zimbabwe:", ody("twemoji/flags/flag_zimbabwe.png"), "🇿🇼"),
    EmoteDef(":flag_england:", ody("twemoji/flags/flag_england.png"), "🏴󠁧󠁢󠁥󠁮󠁧󠁿"),
    EmoteDef(":flag_scotland:", ody("twemoji/flags/flag_scotland.png"), "🏴󠁧󠁢󠁳󠁣󠁴󠁿"),
    EmoteDef(":flag_wales:", ody("twemoji/flags/flag_wales.png"), "🏴󠁧󠁢󠁷󠁬󠁳󠁿"),
    EmoteDef(":flag_european_union:", ody("twemoji/flags/flag_european_union.png"), "🇪🇺"),
    EmoteDef(":flag_united_nations:", ody("twemoji/flags/flag_united_nations.png"), "🇺🇳"),
    EmoteDef(":pirate_flag:", ody("twemoji/flags/pirate_flag.png"), "🏴‍☠️"),
    EmoteDef(":rainbow_flag:", ody("twemoji/flags/rainbow_flag.png"), "🏳️‍🌈"),
    EmoteDef(":transgender_flag:", ody("twemoji/flags/transgender_flag.png"), "🏳️‍⚧️"),
    EmoteDef(":kek_flag:", ody("twemoji/flags/kek_flag.png"), ":kek_flag:"),
    EmoteDef(":anarchocapitalism_flag:", ody("twemoji/flags/anarchocapitalism_flag.png"), ":anarchocapitalism_flag:"),
    EmoteDef(":communism_flag:", ody("twemoji/flags/communism_flag.png"), ":communism_flag:"),
    EmoteDef(":antifa_flag:", ody("twemoji/flags/antifa_flag.png"), ":antifa_flag:"),
    EmoteDef(":gadsden_flag:", ody("twemoji/flags/gadsden_flag.png"), ":gadsden_flag:"),
    EmoteDef(":white_flag:", ody("twemoji/flags/white_flag.png"), "🏳"),
    EmoteDef(":black_flag:", ody("twemoji/flags/black_flag.png"), "🏴"),
)

data class EmoteCategory(val key: String, val title: String, val mainImg: String, val items: List<EmoteDef>)

val EMOTE_CATEGORIES = listOf(
    EmoteCategory("odysee", "Odysee", ody("48%20px/smile%402x.png"), ODYSEE_EMOTES_48),
    EmoteCategory("smilies", "Smilies", ody("twemoji/smilies/grinning.png"), TWEMOTES_SMILIES),
    EmoteCategory("handsignals", "Hand signals", ody("twemoji/handsignals/waving_hand.png"), TWEMOTES_HANDSIGNALS),
    EmoteCategory("activities", "Activities", ody("twemoji/activities/tennis.png"), TWEMOTES_ACTIVITIES),
    EmoteCategory("symbols", "Symbols", ody("twemoji/symbols/sparkling_heart.png"), TWEMOTES_SYMBOLS),
    EmoteCategory("nature", "Animals & Nature", ody("twemoji/nature/dolphin.png"), TWEMOTES_NATURE),
    EmoteCategory("food", "Food & Drink", ody("twemoji/food/sushi.png"), TWEMOTES_FOOD),
    EmoteCategory("flags", "Flags", ody("twemoji/flags/pirate_flag.png"), TWEMOTES_FLAGS),
)

private val EMOTE_TOKEN = Regex(":[a-zA-Z0-9_]+:")

private val ALL_EMOTES_BY_NAME: Map<String, EmoteDef> = buildMap {
    for (cat in EMOTE_CATEGORIES) for (e in cat.items) put(e.name, e)
}

fun emoteByName(name: String): EmoteDef? = ALL_EMOTES_BY_NAME[name]

fun parseEmoteTokens(body: String): List<EmoteSegment> {
    if (!body.contains(":")) return listOf(EmoteSegment(text = body, emote = null))
    val out = mutableListOf<EmoteSegment>()
    var cursor = 0
    EMOTE_TOKEN.findAll(body).forEach { m ->
        val def = ALL_EMOTES_BY_NAME[m.value]
        if (def != null) {
            if (m.range.first > cursor) out.add(EmoteSegment(text = body.substring(cursor, m.range.first), emote = null))
            out.add(EmoteSegment(text = null, emote = def))
            cursor = m.range.last + 1
        }
    }
    if (cursor < body.length) out.add(EmoteSegment(text = body.substring(cursor), emote = null))
    return out
}

data class EmoteSegment(val text: String?, val emote: EmoteDef?)
