name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    # TODO: paths-ignore
  push:
    branches:
      - master
      - gh-actions
    # TODO: paths-ignore

jobs:
  build-full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: gradle/wrapper-validation-action@v1

      - name: Create and checkout branch
        # push events already checked out the branch
        if: github.event_name == 'pull_request'
        run: git checkout -B ${{ github.head_ref }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Copy sample twitter.properties file
        run: cp app/twitter.properties.sample app/twitter.properties

      - name: Copy sample google-services.json file
        run: cp app/google-services.sample.json app/google-services.json

      - name: Build
        run: ./gradlew lintVitalFullRelease assembleFullDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-full
          path: app/build/outputs/apk/full/debug/*.apk

  build-foss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: gradle/wrapper-validation-action@v1

      - name: Create and checkout branch
        # push events already checked out the branch
        if: github.event_name == 'pull_request'
        run: git checkout -B ${{ github.head_ref }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Remove Twitter properties resValue lines
        run: sed -i '/\s*Properties twitterProps/,/\s*resValue "string", "TWITTER_CONSUMER_SECRET"/d' app/build.gradle

      - name: Build
        run: ./gradlew lintVitalFossRelease assembleFossDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-foss
          path: app/build/outputs/apk/foss/debug/*.apk
